### ISSUE TITLE
Any progress?

### ISSUE THREAD

**Issue by rockmandash** [mikerourke/lowasm#1]
Any progress?

**Comment by mikerourke** [comment]
@rockmandash Sadly, no. JavaScript makes it really easy to create and add properties to objects dynamically. C and C++ are very specific about memory allocation and object definitions. I haven't had a chance to dig too deeply into it. I'll have to read the documentation on `ArrayBuffer` and memory allocation for WebAssembly. I'm planning on focusing my efforts on the library much more in the new year. If you have some experience with this, I'd love to hear it.

**Comment by rockmandash** [comment]
@mikerourke It's fine!
